# Basic configuration
owner: IdrisFallout # Your GitHub organization or username
repo: upptime # The name of your repository

# Sites to monitor
sites:
  - name: Website
    url: https://waithakasam.com
  - name: GeminiAIChatBot
    url: https://chat.waithakasam.com
  - name: Swila
    url: https://swila.waithakasam.com

# Status website settings
status-website:
  cname: status.waithakasam.com # Custom domain for the status page
  # baseUrl: /upptime # Uncomment if not using a custom domain
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg # You can replace this with your own logo
  name: IdrisFallout Status # Custom name for your status page
  introTitle: "Welcome to the **IdrisFallout** Status Page" # Custom introduction title
  introMessage: |
    Here you can find the current status and uptime of our services.
    We monitor the uptime of our websites using **Upptime**. Real-time data is pulled directly from our [GitHub repository](https://github.com/IdrisFallout/upptime).
    **No server required** — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/IdrisFallout/upptime # Link to your GitHub repository

# Optional configurations (notifications, issues, etc.)
# See https://upptime.js.org/docs/configuration for more details
